version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    tty: true
    depends_on:
      - db
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./:/usr/src/myapp
    ports:
      - "8080:80"
    environment:
      - TZ=Asia/Tokyo

  db:
    image: mysql:8.0.31
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
    ports:
      - 8000:80
